name: FreeRTOS-Kernel Coverity Scan - GCC Posix Demo
on: [push, pull_request]

jobs:

  POSIX-GCC:
    name: Native GCC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the FreeRTOS/FreeRTOS Repository
        uses: actions/checkout@v3
        with:
          ref: main
          repository: FreeRTOS/FreeRTOS
          submodules: 'recursive'
          fetch-depth: 1

      # Checkout user pull request changes
      - name: Checkout Pull Request
        uses: actions/checkout@v3
        with:
          path: ./FreeRTOS/Source

      - name: Install GCC
        shell: bash
        run: |
          sudo apt-get -y update
          sudo apt-get -y install build-essential

      - name: Install Coverity Build
        shell: bash
        env:
          COVERITY_TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
        run: |
          wget -nv -qO- https://scan.coverity.com/download/linux64 --post-data "token=${COVERITY_TOKEN}&project=FreeRTOS-Kernel" | tar -zx --one-top-level=cov_scan --strip-components 1
          echo "cov_scan_path=cov_scan/bin" >> $GITHUB_ENV

      - name: Build Posix_GCC Demo
        shell: bash
        working-directory: FreeRTOS/Demo/Posix_GCC
        run: |
          export PATH="$PATH:${{env.cov_scan_path}}"
          cov-build --dir cov-int make -j